obj-m := HelloWorldMain.o
HelloWorldMain-objs := HelloWorld.o MultiFile.o

KDIR := /lib/modules/$(shell uname -r)/build

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

